/**
 * Associations
 * Associations define the relationships between objects in HubSpot. These endpoints allow you to create, read, and remove associations.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicAssociation } from '../models/PublicAssociation';
import { StandardError } from '../models/StandardError';

export class BatchResponsePublicAssociationWithErrors {
    'completedAt': Date;
    'errors'?: Array<StandardError>;
    'links'?: { [key: string]: string; };
    'numErrors'?: number;
    'requestedAt'?: Date;
    'results': Array<PublicAssociation>;
    'startedAt': Date;
    'status': BatchResponsePublicAssociationWithErrorsStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<StandardError>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "numErrors",
            "baseName": "numErrors",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "requestedAt",
            "baseName": "requestedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<PublicAssociation>",
            "format": ""
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchResponsePublicAssociationWithErrorsStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchResponsePublicAssociationWithErrors.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BatchResponsePublicAssociationWithErrorsStatusEnum {
    Canceled = 'CANCELED',
    Complete = 'COMPLETE',
    Pending = 'PENDING',
    Processing = 'PROCESSING'
}

