/**
 * CRM Imports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { PublicImportMetadata } from './publicImportMetadata';

/**
* A current summary of the import, whether complete or not.
*/
export class PublicImportResponse {
    'createdAt': Date;
    'metadata': PublicImportMetadata;
    'updatedAt': Date;
    /**
    * The status of the import.
    */
    'state': PublicImportResponse.StateEnum;
    'importRequestJson'?: object;
    /**
    * Whether or not the import is a list of people disqualified from receiving emails.
    */
    'optOutImport': boolean;
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "PublicImportMetadata"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "PublicImportResponse.StateEnum"
        },
        {
            "name": "importRequestJson",
            "baseName": "importRequestJson",
            "type": "object"
        },
        {
            "name": "optOutImport",
            "baseName": "optOutImport",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PublicImportResponse.attributeTypeMap;
    }
}

export namespace PublicImportResponse {
    export enum StateEnum {
        STARTED = <any> 'STARTED',
        PROCESSING = <any> 'PROCESSING',
        DONE = <any> 'DONE',
        FAILED = <any> 'FAILED',
        CANCELED = <any> 'CANCELED'
    }
}
