/**
 * CRM Imports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var CollectionResponsePublicImportErrorForwardPaging = (function () {
    function CollectionResponsePublicImportErrorForwardPaging() {
    }
    CollectionResponsePublicImportErrorForwardPaging.readonly = discriminator;
    return CollectionResponsePublicImportErrorForwardPaging;
})();
exports.CollectionResponsePublicImportErrorForwardPaging = CollectionResponsePublicImportErrorForwardPaging;
string | undefined;
undefined;
readonly;
attributeTypeMap: Array < { name: string, baseName: string, type: string, format: string } > ;
[
    {
        "name": "results",
        "baseName": "results",
        "type": "Array<PublicImportError>",
        "format": ""
    },
    {
        "name": "paging",
        "baseName": "paging",
        "type": "ForwardPaging",
        "format": ""
    }];
getAttributeTypeMap();
{
    return CollectionResponsePublicImportErrorForwardPaging.attributeTypeMap;
}
constructor();
{
}
