/**
 * CRM Imports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicImportMetadata } from './PublicImportMetadata';
import { HttpFile } from '../http/http';

/**
* A current summary of the import, whether complete or not.
*/
export class PublicImportResponse {
    /**
    * The status of the import.
    */
    'state': PublicImportResponseStateEnum;
    'importRequestJson'?: any;
    'createdAt': Date;
    'metadata': PublicImportMetadata;
    'importName'?: string;
    'updatedAt': Date;
    /**
    * Whether or not the import is a list of people disqualified from receiving emails.
    */
    'optOutImport': boolean;
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "state",
            "baseName": "state",
            "type": "PublicImportResponseStateEnum",
            "format": ""
        },
        {
            "name": "importRequestJson",
            "baseName": "importRequestJson",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "PublicImportMetadata",
            "format": ""
        },
        {
            "name": "importName",
            "baseName": "importName",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "optOutImport",
            "baseName": "optOutImport",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicImportResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PublicImportResponseStateEnum = "STARTED" | "PROCESSING" | "DONE" | "FAILED" | "CANCELED" | "DEFERRED" ;

