/**
 * Custom Workflow Actions
 * Create custom workflow actions
 *
 * OpenAPI spec version: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* A serverless function associated with this custom workflow action.
*/
var ActionFunctionIdentifier = (function () {
    function ActionFunctionIdentifier() {
    }
    ActionFunctionIdentifier.readonly = discriminator;
    return ActionFunctionIdentifier;
})();
exports.ActionFunctionIdentifier = ActionFunctionIdentifier;
string | undefined;
undefined;
readonly;
attributeTypeMap: Array < { name: string, baseName: string, type: string, format: string } > ;
[
    {
        "name": "functionType",
        "baseName": "functionType",
        "type": "ActionFunctionIdentifierFunctionTypeEnum",
        "format": ""
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string",
        "format": ""
    }];
getAttributeTypeMap();
{
    return ActionFunctionIdentifier.attributeTypeMap;
}
constructor();
{
}
"PRE_ACTION_EXECUTION" | "PRE_FETCH_OPTIONS" | "POST_FETCH_OPTIONS";
