/**
 * Automation Actions V4
 * Basepom for all HubSpot Projects
 *
 * OpenAPI spec version: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BooleanFieldSchema {
    /**
    * Specifies the field type as BOOLEAN, indicating that the field can hold a true or false value.
    */
    'type': BooleanFieldSchemaTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BooleanFieldSchemaTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BooleanFieldSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BooleanFieldSchemaTypeEnum {
    Boolean = 'BOOLEAN'
}

