/**
 * Custom Workflow Actions
 * Create custom workflow actions
 *
 * OpenAPI spec version: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* Any information to send back to Workflows when completing an action callback as part of a batch request.
*/
var CallbackCompletionBatchRequest = (function () {
    function CallbackCompletionBatchRequest() {
    }
    CallbackCompletionBatchRequest.readonly = discriminator;
    return CallbackCompletionBatchRequest;
})();
exports.CallbackCompletionBatchRequest = CallbackCompletionBatchRequest;
string | undefined;
undefined;
readonly;
attributeTypeMap: Array < { name: string, baseName: string, type: string, format: string } > ;
[
    {
        "name": "callbackId",
        "baseName": "callbackId",
        "type": "string",
        "format": ""
    },
    {
        "name": "outputFields",
        "baseName": "outputFields",
        "type": "{ [key: string]: string; }",
        "format": ""
    }];
getAttributeTypeMap();
{
    return CallbackCompletionBatchRequest.attributeTypeMap;
}
constructor();
{
}
