FROM selenium/standalone-chrome-debug:latest

USER root
WORKDIR /companies-sample-app
COPY sample-apps/companies-app/src/package.json ./sample-apps/companies-app/src/
COPY codegen ./codegen
COPY src ./src
COPY .prettierrc ./
COPY index.ts ./
COPY package.json ./
COPY tsconfig.json ./
COPY tslint.json ./
RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get -y install nodejs
RUN npm install --unsafe-perm
WORKDIR /companies-sample-app/sample-apps/companies-app/src
RUN npm install
