FROM node:10

WORKDIR /contacts-sample-app
COPY sample-apps/contacts-app/src/package.json ./sample-apps/contacts-app/src/
COPY package.json ./
COPY index.js ./
COPY client.js ./
COPY codegen ./codegen
COPY helpers ./helpers
RUN npm install
WORKDIR /contacts-sample-app/sample-apps/contacts-app/src
RUN npm install

EXPOSE 3000
