FROM node:10

WORKDIR /webhooks-sample-app
COPY sample-apps/webhooks-app/src/package.json ./sample-apps/webhooks-app/src/
COPY codegen ./codegen
COPY src ./src
COPY .prettierrc ./
COPY index.ts ./
COPY package.json ./
COPY tsconfig.json ./
COPY tslint.json ./
RUN npm install --unsafe-perm
WORKDIR /webhooks-sample-app/sample-apps/webhooks-app/src
RUN npm install

EXPOSE 3000
