/**
 * Auth Oauth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccessTokenResponse } from '../models/AccessTokenResponse';
import { ClientCredentialsTokenResponse } from '../models/ClientCredentialsTokenResponse';

/**
 * @type TokenResponseIF
 * Type
 * @export
 */
export type TokenResponseIF = AccessTokenResponse | ClientCredentialsTokenResponse;

/**
* @type TokenResponseIFClass
* @export
*/
export class TokenResponseIFClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

