/**
 * Associations
 * Basepom for all HubSpot Projects
 *
 * OpenAPI spec version: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LabelsBetweenObjectPair } from '../models/LabelsBetweenObjectPair';

export class BatchResponseLabelsBetweenObjectPair {
    /**
    * The timestamp when the batch processing was completed, in ISO 8601 format.
    */
    'completedAt': Date;
    /**
    * An object containing relevant links related to the batch request.
    */
    'links'?: { [key: string]: string; };
    /**
    * The timestamp when the batch request was initially made, in ISO 8601 format.
    */
    'requestedAt'?: Date;
    'results': Array<LabelsBetweenObjectPair>;
    /**
    * The timestamp when the batch processing began, in ISO 8601 format.
    */
    'startedAt': Date;
    /**
    * The status of the batch processing request: \"PENDING\", \"PROCESSING\", \"CANCELLED\", or \"COMPLETE\".
    */
    'status': BatchResponseLabelsBetweenObjectPairStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "requestedAt",
            "baseName": "requestedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<LabelsBetweenObjectPair>",
            "format": ""
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchResponseLabelsBetweenObjectPairStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchResponseLabelsBetweenObjectPair.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BatchResponseLabelsBetweenObjectPairStatusEnum {
    Canceled = 'CANCELED',
    Complete = 'COMPLETE',
    Pending = 'PENDING',
    Processing = 'PROCESSING'
}

