/**
 * Blog Post endpoints
 * Use these endpoints for interacting with Blog Posts, Blog Authors, and Blog Tags
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Request body object for creating new language variant content.
*/
export class ContentLanguageCloneRequestVNext {
    /**
    * ID of content to clone.
    */
    'id': string;
    /**
    * Target language of new variant.
    */
    'language'?: string;
    /**
    * Language of primary content to clone.
    */
    'primaryLanguage'?: string;
    'contentGroupId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        },
        {
            "name": "primaryLanguage",
            "baseName": "primaryLanguage",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentGroupId",
            "baseName": "contentGroupId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ContentLanguageCloneRequestVNext.attributeTypeMap;
    }

    public constructor() {
    }
}

