/**
 * Posts
 * Use these endpoints for interacting with Blog Posts, Blog Authors, and Blog Tags
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Angle } from '../models/Angle';
import { ColorStop } from '../models/ColorStop';
import { SideOrCorner } from '../models/SideOrCorner';

export class Gradient {
    'angle': Angle;
    'sideOrCorner': SideOrCorner;
    'colors': Array<ColorStop>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "angle",
            "baseName": "angle",
            "type": "Angle",
            "format": ""
        },
        {
            "name": "sideOrCorner",
            "baseName": "sideOrCorner",
            "type": "SideOrCorner",
            "format": ""
        },
        {
            "name": "colors",
            "baseName": "colors",
            "type": "Array<ColorStop>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Gradient.attributeTypeMap;
    }

    public constructor() {
    }
}

