var AssociationsDiscovery_1 = require('./associations/AssociationsDiscovery');
var CompaniesDiscovery_1 = require('./companies/CompaniesDiscovery');
var ContactsDiscovery_1 = require('./contacts/ContactsDiscovery');
var DealsDiscovery_1 = require('./deals/DealsDiscovery');
var ExtensionsDiscovery_1 = require('./extensions/ExtensionsDiscovery');
var FeedbackSubmissionsDiscovery_1 = require('./feedback_submissions/FeedbackSubmissionsDiscovery');
var ImportsDiscovery_1 = require('./imports/ImportsDiscovery');
var LineItemsDiscovery_1 = require('./line_items/LineItemsDiscovery');
var ObjectsDiscovery_1 = require('./objects/ObjectsDiscovery');
var OwnersDiscovery_1 = require('./owners/OwnersDiscovery');
var PipelinesDiscovery_1 = require('./pipelines/PipelinesDiscovery');
var ProductsDiscovery_1 = require('./products/ProductsDiscovery');
var PropertiesDiscovery_1 = require('./properties/PropertiesDiscovery');
var QuotesDiscovery_1 = require('./quotes/QuotesDiscovery');
var SchemasDiscovery_1 = require('./schemas/SchemasDiscovery');
var TicketsDiscovery_1 = require('./tickets/TicketsDiscovery');
var TimelineDiscovery_1 = require('./timeline/TimelineDiscovery');
var CrmDiscovery = (function () {
    function CrmDiscovery(config) {
        this.associations = new AssociationsDiscovery_1.AssociationsDiscovery(config);
        this.companies = new CompaniesDiscovery_1.CompaniesDiscovery(config);
        this.contacts = new ContactsDiscovery_1.ContactsDiscovery(config);
        this.deals = new DealsDiscovery_1.DealsDiscovery(config);
        this.extensions = new ExtensionsDiscovery_1.ExtensionsDiscovery(config);
        this.feedbackSubmissions = new FeedbackSubmissionsDiscovery_1.FeedbackSubmissionsDiscovery(config);
        this.imports = new ImportsDiscovery_1.ImportsDiscovery(config);
        this.lineItems = new LineItemsDiscovery_1.LineItemsDiscovery(config);
        this.objects = new ObjectsDiscovery_1.ObjectsDiscovery(config);
        this.owners = new OwnersDiscovery_1.OwnersDiscovery(config);
        this.pipelines = new PipelinesDiscovery_1.PipelinesDiscovery(config);
        this.products = new ProductsDiscovery_1.ProductsDiscovery(config);
        this.properties = new PropertiesDiscovery_1.PropertiesDiscovery(config);
        this.quotes = new QuotesDiscovery_1.QuotesDiscovery(config);
        this.schemas = new SchemasDiscovery_1.SchemasDiscovery(config);
        this.tickets = new TicketsDiscovery_1.TicketsDiscovery(config);
        this.timeline = new TimelineDiscovery_1.TimelineDiscovery(config);
    }
    return CrmDiscovery;
})();
exports.CrmDiscovery = CrmDiscovery;
