/**
 * Marketing Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class AttendanceCounters {
    'attended': number;
    'registered': number;
    'cancelled': number;
    'noShows': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attended",
            "baseName": "attended",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "registered",
            "baseName": "registered",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "cancelled",
            "baseName": "cancelled",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "noShows",
            "baseName": "noShows",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return AttendanceCounters.attributeTypeMap;
    }

    public constructor() {
    }
}
