/**
 * Marketing Marketing Events
 * Basepom for all HubSpot Projects
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MarketingEventPublicDefaultResponseV2 } from '../models/MarketingEventPublicDefaultResponseV2';

export class BatchResponseMarketingEventPublicDefaultResponseV2 {
    /**
    * Timestamp of when the request was processed.
    */
    'completedAt': Date;
    /**
    * Result object of the request.
    */
    'links'?: { [key: string]: string; };
    /**
    * Timestamp of when the request was sent.
    */
    'requestedAt'?: Date;
    'results': Array<MarketingEventPublicDefaultResponseV2>;
    /**
    * Timestamp of when the request started processing.
    */
    'startedAt': Date;
    /**
    * The status of the response.
    */
    'status': BatchResponseMarketingEventPublicDefaultResponseV2StatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "requestedAt",
            "baseName": "requestedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<MarketingEventPublicDefaultResponseV2>",
            "format": ""
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchResponseMarketingEventPublicDefaultResponseV2StatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchResponseMarketingEventPublicDefaultResponseV2.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BatchResponseMarketingEventPublicDefaultResponseV2StatusEnum {
    Canceled = 'CANCELED',
    Complete = 'COMPLETE',
    Pending = 'PENDING',
    Processing = 'PROCESSING'
}

