/**
 * Marketing Events Extension
 * These APIs allow you to interact with HubSpot's Marketing Events Extension. It allows you to: * Create, Read or update Marketing Event information in HubSpot * Specify whether a HubSpot contact has registered, attended or cancelled a registration to a Marketing Event. * Specify a URL that can be called to get the details of a Marketing Event. 
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MarketingEventPublicDefaultResponse } from '../models/MarketingEventPublicDefaultResponse';
import { StandardError } from '../models/StandardError';

export class BatchResponseMarketingEventPublicDefaultResponse {
    'completedAt': Date;
    'numErrors'?: number;
    'requestedAt'?: Date;
    'startedAt': Date;
    'links'?: { [key: string]: string; };
    'results': Array<MarketingEventPublicDefaultResponse>;
    'errors'?: Array<StandardError>;
    'status': BatchResponseMarketingEventPublicDefaultResponseStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "numErrors",
            "baseName": "numErrors",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "requestedAt",
            "baseName": "requestedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<MarketingEventPublicDefaultResponse>",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<StandardError>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchResponseMarketingEventPublicDefaultResponseStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchResponseMarketingEventPublicDefaultResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BatchResponseMarketingEventPublicDefaultResponseStatusEnum = "PENDING" | "PROCESSING" | "CANCELED" | "COMPLETE" ;

