/**
 * Timeline events
 * This feature allows an app to create and configure custom events that can show up in the timelines of certain CRM object like contacts, companies, or deals. You\'ll find multiple use cases for this API in the sections below.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { TimelineEventTemplateTokenOption } from './timelineEventTemplateTokenOption';

/**
* State of the token definition for update requests.
*/
export class TimelineEventTemplateTokenUpdateRequest {
    /**
    * Used for list segmentation and reporting.
    */
    'label': string;
    /**
    * The name of the CRM object property. This will populate the CRM object property associated with the event. With enough of these, you can fully build CRM objects via the Timeline API.
    */
    'objectPropertyName'?: string;
    /**
    * If type is `enumeration`, we should have a list of options to choose from.
    */
    'options': Array<TimelineEventTemplateTokenOption>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "objectPropertyName",
            "baseName": "objectPropertyName",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<TimelineEventTemplateTokenOption>"
        }    ];

    static getAttributeTypeMap() {
        return TimelineEventTemplateTokenUpdateRequest.attributeTypeMap;
    }
}

