/**
 * LinkedSalesObjectsPublicService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CardActions } from './cardActions';
import { CardDisplayBody } from './cardDisplayBody';
import { CardFetchBody } from './cardFetchBody';

export class CardResponse {
    'id': string;
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'title': string;
    'fetch': CardFetchBody;
    'display': CardDisplayBody;
    'actions': CardActions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "fetch",
            "baseName": "fetch",
            "type": "CardFetchBody"
        },
        {
            "name": "display",
            "baseName": "display",
            "type": "CardDisplayBody"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "CardActions"
        }    ];

    static getAttributeTypeMap() {
        return CardResponse.attributeTypeMap;
    }
}

