/**
 * Accounting Extension
 * These APIs allow you to interact with HubSpot\'s Accounting Extension. It allows you to: * Specify the URLs that HubSpot will use when making webhook requests to your external accounting system. * Respond to webhook calls made to your external accounting system by HubSpot 
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class InvoiceUpdateResponse {
    'externalInvoiceNumber'?: string;
    'totalAmountBilled': number;
    'balanceDue': number;
    'currencyCode': string;
    'dueDate': string;
    'externalRecipientId': string;
    'receivedByRecipientDate'?: number;
    'externalCreateDateTime'?: number;
    'isVoided': boolean;
    'createdAt': Date;
    'updatedAt': Date;
    'archivedAt'?: Date;
    'archived': boolean;
    'externalAccountId': string;
    'invoiceStatus': InvoiceUpdateResponseInvoiceStatusEnum;
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "externalInvoiceNumber",
            "baseName": "externalInvoiceNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalAmountBilled",
            "baseName": "totalAmountBilled",
            "type": "number",
            "format": ""
        },
        {
            "name": "balanceDue",
            "baseName": "balanceDue",
            "type": "number",
            "format": ""
        },
        {
            "name": "currencyCode",
            "baseName": "currencyCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "string",
            "format": "date"
        },
        {
            "name": "externalRecipientId",
            "baseName": "externalRecipientId",
            "type": "string",
            "format": ""
        },
        {
            "name": "receivedByRecipientDate",
            "baseName": "receivedByRecipientDate",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "externalCreateDateTime",
            "baseName": "externalCreateDateTime",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isVoided",
            "baseName": "isVoided",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "archivedAt",
            "baseName": "archivedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "externalAccountId",
            "baseName": "externalAccountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoiceStatus",
            "baseName": "invoiceStatus",
            "type": "InvoiceUpdateResponseInvoiceStatusEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvoiceUpdateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum InvoiceUpdateResponseInvoiceStatusEnum {
    Created = 'CREATED',
    Sent = 'SENT',
    Paid = 'PAID',
    Closed = 'CLOSED',
    Overdue = 'OVERDUE',
    Voided = 'VOIDED',
    None = 'NONE',
    Unpaid = 'UNPAID'
}

