/**
 * Events Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ExternalUnifiedEvent {
    /**
    * An ISO 8601 timestamp when the event occurred.
    */
    'occurredAt': Date;
    /**
    * The format of the `eventType` string is `ae{appId}_{eventTypeLabel}`, `pe{portalId}_{eventTypeLabel}`, or just `e_{eventTypeLabel}` for HubSpot events.
    */
    'eventType': string;
    /**
    * A unique identifier for the event.
    */
    'id': string;
    /**
    * The objectId of the object which did the event.
    */
    'objectId': string;
    'properties'?: { [key: string]: string; };
    /**
    * The objectType for the object which did the event.
    */
    'objectType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "occurredAt",
            "baseName": "occurredAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "objectType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalUnifiedEvent.attributeTypeMap;
    }

    public constructor() {
    }
}
