/**
 * CMS Performance API
 * Use these endpoints to get a time series view of your website\'s performance.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* An individual time series performance data point.
*/
export class PerformanceView {
    /**
    * The number of responses that had an http status code of 403.
    */
    '_403': number;
    /**
    * The number of responses that had an http status code of 404.
    */
    '_404': number;
    /**
    * The number of responses that had an http status code of 500.
    */
    '_500': number;
    /**
    * The number of responses that had an http status code of 504.
    */
    '_504': number;
    /**
    * The timestamp in milliseconds of the start of this interval.
    */
    'startTimestamp': number;
    /**
    * The timestamp in milliseconds of the end of this interval.
    */
    'endTimestamp': number;
    'startDatetime': string;
    'endDatetime': string;
    /**
    * The total number of requests received in this period.
    */
    'totalRequests': number;
    /**
    * The total number of requests that were served cached responses.
    */
    'cacheHits': number;
    /**
    * The percentage of requests that were served cached responses.
    */
    'cacheHitRate': number;
    'totalRequestTime': number;
    /**
    * The average response time in milliseconds from the origin to the edge.
    */
    'avgOriginResponseTime': number;
    /**
    * The average response time in milliseconds.
    */
    'responseTimeMs': number;
    /**
    * The number of responses that had an http status code between 1000-1999.
    */
    '_100x': number;
    /**
    * The number of responses that had an http status code between 200-299.
    */
    '_20x': number;
    /**
    * The number of responses that had an http status code between 300-399.
    */
    '_30x': number;
    /**
    * The number of responses that had an http status code between 400-499.
    */
    '_40x': number;
    /**
    * The number of responses that had an http status code between 500-599.
    */
    '_50x': number;
    /**
    * The 50th percentile response time.
    */
    '_50th': number;
    /**
    * The 95th percentile response time.
    */
    '_95th': number;
    /**
    * The 99th percentile response time.
    */
    '_99th': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_403",
            "baseName": "403",
            "type": "number"
        },
        {
            "name": "_404",
            "baseName": "404",
            "type": "number"
        },
        {
            "name": "_500",
            "baseName": "500",
            "type": "number"
        },
        {
            "name": "_504",
            "baseName": "504",
            "type": "number"
        },
        {
            "name": "startTimestamp",
            "baseName": "startTimestamp",
            "type": "number"
        },
        {
            "name": "endTimestamp",
            "baseName": "endTimestamp",
            "type": "number"
        },
        {
            "name": "startDatetime",
            "baseName": "startDatetime",
            "type": "string"
        },
        {
            "name": "endDatetime",
            "baseName": "endDatetime",
            "type": "string"
        },
        {
            "name": "totalRequests",
            "baseName": "totalRequests",
            "type": "number"
        },
        {
            "name": "cacheHits",
            "baseName": "cacheHits",
            "type": "number"
        },
        {
            "name": "cacheHitRate",
            "baseName": "cacheHitRate",
            "type": "number"
        },
        {
            "name": "totalRequestTime",
            "baseName": "totalRequestTime",
            "type": "number"
        },
        {
            "name": "avgOriginResponseTime",
            "baseName": "avgOriginResponseTime",
            "type": "number"
        },
        {
            "name": "responseTimeMs",
            "baseName": "responseTimeMs",
            "type": "number"
        },
        {
            "name": "_100x",
            "baseName": "100X",
            "type": "number"
        },
        {
            "name": "_20x",
            "baseName": "20X",
            "type": "number"
        },
        {
            "name": "_30x",
            "baseName": "30X",
            "type": "number"
        },
        {
            "name": "_40x",
            "baseName": "40X",
            "type": "number"
        },
        {
            "name": "_50x",
            "baseName": "50X",
            "type": "number"
        },
        {
            "name": "_50th",
            "baseName": "50th",
            "type": "number"
        },
        {
            "name": "_95th",
            "baseName": "95th",
            "type": "number"
        },
        {
            "name": "_99th",
            "baseName": "99th",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PerformanceView.attributeTypeMap;
    }
}

