/**
 * CMS Performance API
 * Use these endpoints to get a time series view of your website\'s performance.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PerformanceView } from './performanceView';

export class PublicPerformanceResponse {
    'data': Array<PerformanceView>;
    'domain'?: string;
    'path'?: string;
    'startInterval': number;
    'endInterval': number;
    'interval': PublicPerformanceResponse.IntervalEnum;
    'period'?: PublicPerformanceResponse.PeriodEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<PerformanceView>"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "startInterval",
            "baseName": "startInterval",
            "type": "number"
        },
        {
            "name": "endInterval",
            "baseName": "endInterval",
            "type": "number"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "PublicPerformanceResponse.IntervalEnum"
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "PublicPerformanceResponse.PeriodEnum"
        }    ];

    static getAttributeTypeMap() {
        return PublicPerformanceResponse.attributeTypeMap;
    }
}

export namespace PublicPerformanceResponse {
    export enum IntervalEnum {
        OneMinute = <any> 'ONE_MINUTE',
        FiveMinutes = <any> 'FIVE_MINUTES',
        TenMinutes = <any> 'TEN_MINUTES',
        FifteenMinutes = <any> 'FIFTEEN_MINUTES',
        ThirtyMinutes = <any> 'THIRTY_MINUTES',
        OneHour = <any> 'ONE_HOUR',
        FourHours = <any> 'FOUR_HOURS',
        TwelveHours = <any> 'TWELVE_HOURS',
        OneDay = <any> 'ONE_DAY',
        OneWeek = <any> 'ONE_WEEK'
    }
    export enum PeriodEnum {
        OneMinute = <any> 'ONE_MINUTE',
        FiveMinutes = <any> 'FIVE_MINUTES',
        TenMinutes = <any> 'TEN_MINUTES',
        FifteenMinutes = <any> 'FIFTEEN_MINUTES',
        ThirtyMinutes = <any> 'THIRTY_MINUTES',
        OneHour = <any> 'ONE_HOUR',
        FourHours = <any> 'FOUR_HOURS',
        TwelveHours = <any> 'TWELVE_HOURS',
        OneDay = <any> 'ONE_DAY',
        OneWeek = <any> 'ONE_WEEK'
    }
}
