/**
 * CRM Exports
 * Basepom for all HubSpot Projects
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicExportResponse {
    /**
    * The timestamp when the export was created, in ISO 8601 format.
    */
    'createdAt': Date;
    /**
    * The name assigned to the export.
    */
    'exportName'?: string;
    /**
    * The current state of the export process.
    */
    'exportState': PublicExportResponseExportStateEnum;
    /**
    * The type of export, which can be either VIEW or LIST.
    */
    'exportType': PublicExportResponseExportTypeEnum;
    /**
    * The unique ID of the export.
    */
    'id': string;
    /**
    * The list of properties exported for the associated object.
    */
    'objectProperties': Array<string>;
    /**
    * The associated CRM object being exported.
    */
    'objectType': string;
    /**
    * The total number of records included in the export.
    */
    'recordCount'?: number;
    /**
    * The timestamp when the export was last updated, in ISO 8601 format.
    */
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "exportName",
            "baseName": "exportName",
            "type": "string",
            "format": ""
        },
        {
            "name": "exportState",
            "baseName": "exportState",
            "type": "PublicExportResponseExportStateEnum",
            "format": ""
        },
        {
            "name": "exportType",
            "baseName": "exportType",
            "type": "PublicExportResponseExportTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectProperties",
            "baseName": "objectProperties",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "objectType",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordCount",
            "baseName": "recordCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PublicExportResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicExportResponseExportStateEnum {
    Canceled = 'CANCELED',
    Conflict = 'CONFLICT',
    Deferred = 'DEFERRED',
    Deleted = 'DELETED',
    Done = 'DONE',
    Enqueued = 'ENQUEUED',
    Failed = 'FAILED',
    PendingApproval = 'PENDING_APPROVAL',
    Processing = 'PROCESSING'
}
export enum PublicExportResponseExportTypeEnum {
    List = 'LIST',
    View = 'VIEW'
}

