/**
 * Transactional Email
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Paging } from './Paging';
import { SmtpApiTokenView } from './SmtpApiTokenView';
import { HttpFile } from '../http/http';

/**
* A collection of SMTP API tokens.
*/
export class CollectionResponseSmtpApiTokenView {
    /**
    * The actual collection of tokens.
    */
    'results': Array<SmtpApiTokenView>;
    'paging'?: Paging;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<SmtpApiTokenView>",
            "format": ""
        },
        {
            "name": "paging",
            "baseName": "paging",
            "type": "Paging",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionResponseSmtpApiTokenView.attributeTypeMap;
    }
    
    public constructor() {
    }
}

