/**
 * Transactional Single Send
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SmtpApiTokenRequestEgg {
    /**
    * A name for the campaign tied to the SMTP API token.
    */
    'campaignName': string;
    /**
    * Indicates whether a contact should be created for email recipients.
    */
    'createContact': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "campaignName",
            "baseName": "campaignName",
            "type": "string",
            "format": ""
        },
        {
            "name": "createContact",
            "baseName": "createContact",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SmtpApiTokenRequestEgg.attributeTypeMap;
    }

    public constructor() {
    }
}
