/**
 * Timeline events
 * This feature allows an app to create and configure custom events that can show up in the timelines of certain CRM objects like contacts, companies, tickets, or deals. You\'ll find multiple use cases for this API in the sections below.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TimelineEventIFrame } from './timelineEventIFrame';

/**
* The state of the timeline event.
*/
export class TimelineEvent {
    /**
    * The event template ID.
    */
    'eventTemplateId': string;
    /**
    * The email address used for contact-specific events. This can be used to identify existing contacts, create new ones, or change the email for an existing contact (if paired with the `objectId`).
    */
    'email'?: string;
    /**
    * The CRM object identifier. This is required for every event other than contacts (where utk or email can be used).
    */
    'objectId'?: string;
    /**
    * Use the `utk` parameter to associate an event with a contact by `usertoken`. This is recommended if you don\'t know a user\'s email, but have an identifying user token in your cookie.
    */
    'utk'?: string;
    /**
    * The event domain (often paired with utk).
    */
    'domain'?: string;
    /**
    * The time the event occurred. If not passed in, the curren time will be assumed. This is used to determine where an event is shown on a CRM object\'s timeline.
    */
    'timestamp'?: Date;
    /**
    * A collection of token keys and values associated with the template tokens.
    */
    'tokens': { [key: string]: string; };
    /**
    * Additional event-specific data that can be interpreted by the template\'s markdown.
    */
    'extraData'?: object;
    'timelineIFrame'?: TimelineEventIFrame;
    /**
    * Identifier for the event. This is optional, and we recommend you do not pass this in. We will create one for you if you omit this. You can also use `{{uuid}}` anywhere in the ID to generate a unique string, guaranteeing uniqueness.
    */
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventTemplateId",
            "baseName": "eventTemplateId",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string"
        },
        {
            "name": "utk",
            "baseName": "utk",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "extraData",
            "baseName": "extraData",
            "type": "object"
        },
        {
            "name": "timelineIFrame",
            "baseName": "timelineIFrame",
            "type": "TimelineEventIFrame"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TimelineEvent.attributeTypeMap;
    }
}

