/**
 * Line Items
 * Why don\'t you just tell me the movie you\'ve selected or the description you expect to see here?
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Paging } from './paging';
import { SimplePublicObject } from './simplePublicObject';

export class CollectionResponseWithTotalSimplePublicObject {
    /**
    * The number of available results
    */
    'total': number;
    'results': Array<SimplePublicObject>;
    'paging'?: Paging;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<SimplePublicObject>"
        },
        {
            "name": "paging",
            "baseName": "paging",
            "type": "Paging"
        }    ];

    static getAttributeTypeMap() {
        return CollectionResponseWithTotalSimplePublicObject.attributeTypeMap;
    }
}

