/**
 * Timeline events
 * This feature allows an app to create and configure custom events that can show up in the timelines of certain CRM objects like contacts, companies, tickets, or deals. You'll find multiple use cases for this API in the sections below.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var NextPage = (function () {
    function NextPage() {
    }
    NextPage.readonly = discriminator;
    return NextPage;
})();
exports.NextPage = NextPage;
string | undefined;
undefined;
readonly;
attributeTypeMap: Array < { name: string, baseName: string, type: string, format: string } > ;
[
    {
        "name": "after",
        "baseName": "after",
        "type": "string",
        "format": ""
    },
    {
        "name": "link",
        "baseName": "link",
        "type": "string",
        "format": ""
    }];
getAttributeTypeMap();
{
    return NextPage.attributeTypeMap;
}
constructor();
{
}
