/**
 * Communications
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Filter {
    'highValue'?: string;
    'propertyName': string;
    'values'?: Array<string>;
    'value'?: string;
    /**
    * null
    */
    'operator': FilterOperatorEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "highValue",
            "baseName": "highValue",
            "type": "string",
            "format": ""
        },
        {
            "name": "propertyName",
            "baseName": "propertyName",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FilterOperatorEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Filter.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum FilterOperatorEnum {
    Eq = 'EQ',
    Neq = 'NEQ',
    Lt = 'LT',
    Lte = 'LTE',
    Gt = 'GT',
    Gte = 'GTE',
    Between = 'BETWEEN',
    In = 'IN',
    NotIn = 'NOT_IN',
    HasProperty = 'HAS_PROPERTY',
    NotHasProperty = 'NOT_HAS_PROPERTY',
    ContainsToken = 'CONTAINS_TOKEN',
    NotContainsToken = 'NOT_CONTAINS_TOKEN'
}

