/**
 * Blog Post endpoints
 * \"Use these endpoints for interacting with Blog Posts, Blog Authors, and Blog Tags\"
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BackgroundImage {
    'imageUrl': string;
    'backgroundSize': string;
    'backgroundPosition': BackgroundImage.BackgroundPositionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string"
        },
        {
            "name": "backgroundSize",
            "baseName": "backgroundSize",
            "type": "string"
        },
        {
            "name": "backgroundPosition",
            "baseName": "backgroundPosition",
            "type": "BackgroundImage.BackgroundPositionEnum"
        }    ];

    static getAttributeTypeMap() {
        return BackgroundImage.attributeTypeMap;
    }
}

export namespace BackgroundImage {
    export enum BackgroundPositionEnum {
        TopLeft = <any> 'TOP_LEFT',
        TopCenter = <any> 'TOP_CENTER',
        TopRight = <any> 'TOP_RIGHT',
        MiddleLeft = <any> 'MIDDLE_LEFT',
        MiddleCenter = <any> 'MIDDLE_CENTER',
        MiddleRight = <any> 'MIDDLE_RIGHT',
        BottomLeft = <any> 'BOTTOM_LEFT',
        BottomCenter = <any> 'BOTTOM_CENTER',
        BottomRight = <any> 'BOTTOM_RIGHT'
    }
}
