/**
 * Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicObjectList } from '../models/PublicObjectList';

/**
* The response object containing the lists found for a multi-list fetch.
*/
export class ListsByIdResponse {
    /**
    * The object list definitions.
    */
    'lists': Array<PublicObjectList>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lists",
            "baseName": "lists",
            "type": "Array<PublicObjectList>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListsByIdResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

