/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicAndFilterBranch } from '../models/PublicAndFilterBranch';
import { PublicAssociationFilterBranch } from '../models/PublicAssociationFilterBranch';
import { PublicNotAllFilterBranch } from '../models/PublicNotAllFilterBranch';
import { PublicNotAnyFilterBranch } from '../models/PublicNotAnyFilterBranch';
import { PublicOrFilterBranch } from '../models/PublicOrFilterBranch';
import { PublicPropertyAssociationFilterBranch } from '../models/PublicPropertyAssociationFilterBranch';
import { PublicRestrictedFilterBranch } from '../models/PublicRestrictedFilterBranch';
import { PublicUnifiedEventsFilterBranch } from '../models/PublicUnifiedEventsFilterBranch';

/**
 * @type PublicPropertyAssociationFilterBranchFilterBranchesInner
 * Type
 * @export
 */
export type PublicPropertyAssociationFilterBranchFilterBranchesInner = PublicAndFilterBranch | PublicAssociationFilterBranch | PublicNotAllFilterBranch | PublicNotAnyFilterBranch | PublicOrFilterBranch | PublicPropertyAssociationFilterBranch | PublicRestrictedFilterBranch | PublicUnifiedEventsFilterBranch;

/**
* @type PublicPropertyAssociationFilterBranchFilterBranchesInnerClass
* @export
*/
export class PublicPropertyAssociationFilterBranchFilterBranchesInnerClass {
    static readonly discriminator: string | undefined = "filterBranchType";

    static readonly mapping: {[index: string]: string} | undefined = {
        "AND": "PublicAndFilterBranch",
        "ASSOCIATION": "PublicAssociationFilterBranch",
        "NOT_ALL": "PublicNotAllFilterBranch",
        "NOT_ANY": "PublicNotAnyFilterBranch",
        "OR": "PublicOrFilterBranch",
        "PROPERTY_ASSOCIATION": "PublicPropertyAssociationFilterBranch",
        "RESTRICTED": "PublicRestrictedFilterBranch",
        "UNIFIED_EVENTS": "PublicUnifiedEventsFilterBranch",
    };
}







