/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicPrivacyAnalyticsFilter {
    /**
    * Specifies the type of filter (PRIVACY).
    */
    'filterType': PublicPrivacyAnalyticsFilterFilterTypeEnum;
    /**
    * Defines the operation to be applied within the filter (PRIVACY_CONSENT_GRANTED, PRIVACY_CONSENT_NOT_GRANTED).
    */
    'operator': string;
    /**
    * The name of the privacy setting used in the filter.
    */
    'privacyName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "PublicPrivacyAnalyticsFilterFilterTypeEnum",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "string",
            "format": ""
        },
        {
            "name": "privacyName",
            "baseName": "privacyName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicPrivacyAnalyticsFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicPrivacyAnalyticsFilterFilterTypeEnum {
    Privacy = 'PRIVACY'
}

