/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicSurveyMonkeyValueFilterValueComparison } from '../models/PublicSurveyMonkeyValueFilterValueComparison';

export class PublicSurveyMonkeyValueFilter {
    /**
    * Defines the type of filter (SURVEY_MONKEY_VALUE).
    */
    'filterType': PublicSurveyMonkeyValueFilterFilterTypeEnum;
    /**
    * Defines the operation to be applied within the filter (HAS_ANSWERED_SURVEY_QUESTION_WITH_VALUE).
    */
    'operator': string;
    /**
    * The column ID of the survey answer used in the filter.
    */
    'surveyAnswerColId'?: string;
    /**
    * The row ID of the survey answer used in the filter.
    */
    'surveyAnswerRowId'?: string;
    /**
    * The ID of the survey used in the filter.
    */
    'surveyId': string;
    /**
    * The question from the survey used in the filter.
    */
    'surveyQuestion': string;
    'valueComparison': PublicSurveyMonkeyValueFilterValueComparison;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "PublicSurveyMonkeyValueFilterFilterTypeEnum",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "string",
            "format": ""
        },
        {
            "name": "surveyAnswerColId",
            "baseName": "surveyAnswerColId",
            "type": "string",
            "format": ""
        },
        {
            "name": "surveyAnswerRowId",
            "baseName": "surveyAnswerRowId",
            "type": "string",
            "format": ""
        },
        {
            "name": "surveyId",
            "baseName": "surveyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "surveyQuestion",
            "baseName": "surveyQuestion",
            "type": "string",
            "format": ""
        },
        {
            "name": "valueComparison",
            "baseName": "valueComparison",
            "type": "PublicSurveyMonkeyValueFilterValueComparison",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicSurveyMonkeyValueFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicSurveyMonkeyValueFilterFilterTypeEnum {
    SurveyMonkeyValue = 'SURVEY_MONKEY_VALUE'
}

