/**
 * Lists
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicFormSubmissionFilterCoalescingRefineBy } from '../models/PublicFormSubmissionFilterCoalescingRefineBy';

export class PublicFormSubmissionOnPageFilter {
    'formId'?: string;
    'coalescingRefineBy'?: PublicFormSubmissionFilterCoalescingRefineBy;
    'pruningRefineBy'?: PublicFormSubmissionFilterCoalescingRefineBy;
    'filterType': PublicFormSubmissionOnPageFilterFilterTypeEnum;
    'pageId': string;
    'operator': PublicFormSubmissionOnPageFilterOperatorEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "formId",
            "baseName": "formId",
            "type": "string",
            "format": ""
        },
        {
            "name": "coalescingRefineBy",
            "baseName": "coalescingRefineBy",
            "type": "PublicFormSubmissionFilterCoalescingRefineBy",
            "format": ""
        },
        {
            "name": "pruningRefineBy",
            "baseName": "pruningRefineBy",
            "type": "PublicFormSubmissionFilterCoalescingRefineBy",
            "format": ""
        },
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "PublicFormSubmissionOnPageFilterFilterTypeEnum",
            "format": ""
        },
        {
            "name": "pageId",
            "baseName": "pageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "PublicFormSubmissionOnPageFilterOperatorEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicFormSubmissionOnPageFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicFormSubmissionOnPageFilterFilterTypeEnum {
    FormSubmissionOnPage = 'FORM_SUBMISSION_ON_PAGE'
}
export enum PublicFormSubmissionOnPageFilterOperatorEnum {
    FilledOut = 'FILLED_OUT',
    NotFilledOut = 'NOT_FILLED_OUT'
}

