/**
 * Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicInListFilterMetadata {
    'id': string;
    'inListType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "inListType",
            "baseName": "inListType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicInListFilterMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

