/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicListConversionResponseRequestedConversionTime } from '../models/PublicListConversionResponseRequestedConversionTime';

export class PublicListConversionResponse {
    'listId': string;
    'requestedConversionTime'?: PublicListConversionResponseRequestedConversionTime;
    'convertedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "listId",
            "baseName": "listId",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestedConversionTime",
            "baseName": "requestedConversionTime",
            "type": "PublicListConversionResponseRequestedConversionTime",
            "format": ""
        },
        {
            "name": "convertedAt",
            "baseName": "convertedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PublicListConversionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
