/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicNumberPropertyOperation {
    /**
    * Indicates whether objects with no value set for the property should be included in the operation.
    */
    'includeObjectsWithNoValueSet': boolean;
    /**
    * Specifies the type of operation (NUMBER).
    */
    'operationType': PublicNumberPropertyOperationOperationTypeEnum;
    /**
    * Defines the operation to be applied in the number property operation (IS_EQUAL_TO, IS_NOT_EQUAL_TO, IS_GREATER_THAN, IS_GREATER_THAN_OR_EQUAL_TO, IS_LESS_THAN, IS_LESS_THAN_OR_EQUAL_TO, HAS_EVER_BEEN_EQUAL_TO, HAS_NEVER_BEEN_EQUAL_TO).
    */
    'operator': string;
    /**
    * The numeric value to be used in the operation.
    */
    'value': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "includeObjectsWithNoValueSet",
            "baseName": "includeObjectsWithNoValueSet",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "operationType",
            "baseName": "operationType",
            "type": "PublicNumberPropertyOperationOperationTypeEnum",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicNumberPropertyOperation.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicNumberPropertyOperationOperationTypeEnum {
    Number = 'NUMBER'
}

