/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicTimeOffset } from '../models/PublicTimeOffset';

export class PublicRelativeRangedTimestampRefineBy {
    'upperBoundOffset': PublicTimeOffset;
    'rangeType': string;
    'lowerBoundOffset': PublicTimeOffset;
    'type': PublicRelativeRangedTimestampRefineByTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "upperBoundOffset",
            "baseName": "upperBoundOffset",
            "type": "PublicTimeOffset",
            "format": ""
        },
        {
            "name": "rangeType",
            "baseName": "rangeType",
            "type": "string",
            "format": ""
        },
        {
            "name": "lowerBoundOffset",
            "baseName": "lowerBoundOffset",
            "type": "PublicTimeOffset",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PublicRelativeRangedTimestampRefineByTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicRelativeRangedTimestampRefineBy.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicRelativeRangedTimestampRefineByTypeEnum {
    RelativeRanged = 'RELATIVE_RANGED'
}

