/**
 * Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicEventFilterMetadata } from '../models/PublicEventFilterMetadata';

export class PublicIntegrationEventFilter {
    'filterType': PublicIntegrationEventFilterFilterTypeEnum;
    'eventTypeId': number;
    'filterLines': Array<PublicEventFilterMetadata>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "PublicIntegrationEventFilterFilterTypeEnum",
            "format": ""
        },
        {
            "name": "eventTypeId",
            "baseName": "eventTypeId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "filterLines",
            "baseName": "filterLines",
            "type": "Array<PublicEventFilterMetadata>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicIntegrationEventFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PublicIntegrationEventFilterFilterTypeEnum {
    IntegrationEvent = 'INTEGRATION_EVENT'
}

