/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicCommunicationSubscriptionFilter {
    'acceptedOptStates': Array<string>;
    /**
    * The ID of the business unit associated with the subscription filter.
    */
    'businessUnitId'?: string;
    /**
    * Specifies the communication channel associated with the subscription filter (EMAIL, WHATSAPP, SMS).
    */
    'channel': string;
    /**
    * Indicates the type of filter, which is (COMMUNICATION_SUBSCRIPTION)
    */
    'filterType': PublicCommunicationSubscriptionFilterFilterTypeEnum;
    'subscriptionIds': Array<string>;
    /**
    * Defines the type of subscription related to the filter (PORTAL_WIDE, BUSINESS_UNIT_WIDE, INDIVIDUAL_SUBSCRIPTION)
    */
    'subscriptionType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "acceptedOptStates",
            "baseName": "acceptedOptStates",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "businessUnitId",
            "baseName": "businessUnitId",
            "type": "string",
            "format": ""
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string",
            "format": ""
        },
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "PublicCommunicationSubscriptionFilterFilterTypeEnum",
            "format": ""
        },
        {
            "name": "subscriptionIds",
            "baseName": "subscriptionIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "subscriptionType",
            "baseName": "subscriptionType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicCommunicationSubscriptionFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicCommunicationSubscriptionFilterFilterTypeEnum {
    CommunicationSubscription = 'COMMUNICATION_SUBSCRIPTION'
}

