/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicMultiStringPropertyOperation {
    /**
    * Indicates whether objects with no value set for the property should be included in the operation.
    */
    'includeObjectsWithNoValueSet': boolean;
    /**
    * Specifies the type of operation (MULTISTRING).
    */
    'operationType': PublicMultiStringPropertyOperationOperationTypeEnum;
    /**
    * Defines the operation to be applied in the multi-string property operation (IS_EQUAL_TO, IS_NOT_EQUAL_TO, CONTAINS, CONTAINS_EXACTLY, DOES_NOT_CONTAIN, DOES_NOT_CONTAIN_EXACTLY, STARTS_WITH, ENDS_WITH).
    */
    'operator': string;
    'values': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "includeObjectsWithNoValueSet",
            "baseName": "includeObjectsWithNoValueSet",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "operationType",
            "baseName": "operationType",
            "type": "PublicMultiStringPropertyOperationOperationTypeEnum",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicMultiStringPropertyOperation.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicMultiStringPropertyOperationOperationTypeEnum {
    Multistring = 'MULTISTRING'
}

