/**
 * Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicIndexOffset } from '../models/PublicIndexOffset';
import { PublicIndexedTimePointIndexReference } from '../models/PublicIndexedTimePointIndexReference';

export class PublicTimePointOperationTimePoint {
    'timeType': PublicTimePointOperationTimePointTimeTypeEnum;
    'timezoneSource'?: string;
    'zoneId': string;
    'year': number;
    'month': number;
    'day': number;
    'hour'?: number;
    'minute'?: number;
    'second'?: number;
    'millisecond'?: number;
    'indexReference': PublicIndexedTimePointIndexReference;
    'offset'?: PublicIndexOffset;
    'property': string;
    'referenceType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeType",
            "baseName": "timeType",
            "type": "PublicTimePointOperationTimePointTimeTypeEnum",
            "format": ""
        },
        {
            "name": "timezoneSource",
            "baseName": "timezoneSource",
            "type": "string",
            "format": ""
        },
        {
            "name": "zoneId",
            "baseName": "zoneId",
            "type": "string",
            "format": ""
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "month",
            "baseName": "month",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "day",
            "baseName": "day",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "hour",
            "baseName": "hour",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "minute",
            "baseName": "minute",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "second",
            "baseName": "second",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "millisecond",
            "baseName": "millisecond",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "indexReference",
            "baseName": "indexReference",
            "type": "PublicIndexedTimePointIndexReference",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "PublicIndexOffset",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": ""
        },
        {
            "name": "referenceType",
            "baseName": "referenceType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicTimePointOperationTimePoint.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PublicTimePointOperationTimePointTimeTypeEnum {
    PropertyReferenced = 'PROPERTY_REFERENCED'
}

