/**
 * CRM Lists
 * CRUD operations to manage lists and list memberships
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicConstantFilter {
    /**
    * Specifies the type of filter, which is (CONSTANT).
    */
    'filterType': PublicConstantFilterFilterTypeEnum;
    /**
    * Indicates whether the filter should accept the condition.
    */
    'shouldAccept': boolean;
    /**
    * Defines the source of the constant filter.
    */
    'source'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "PublicConstantFilterFilterTypeEnum",
            "format": ""
        },
        {
            "name": "shouldAccept",
            "baseName": "shouldAccept",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicConstantFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PublicConstantFilterFilterTypeEnum {
    Constant = 'CONSTANT'
}

