/**
 * Lists
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PublicAbsoluteRangedTimestampRefineBy {
    'rangeType': string;
    'upperTimestamp': number;
    'lowerTimestamp': number;
    'type': PublicAbsoluteRangedTimestampRefineByTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rangeType",
            "baseName": "rangeType",
            "type": "string",
            "format": ""
        },
        {
            "name": "upperTimestamp",
            "baseName": "upperTimestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "lowerTimestamp",
            "baseName": "lowerTimestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PublicAbsoluteRangedTimestampRefineByTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicAbsoluteRangedTimestampRefineBy.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PublicAbsoluteRangedTimestampRefineByTypeEnum {
    AbsoluteRanged = 'ABSOLUTE_RANGED'
}

