/**
 * Pages
 * Use these endpoints for interacting with Landing Pages and Site Pages
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentFolder } from '../models/ContentFolder';

/**
* Response object for successful batch operations on content folders.
*/
export class BatchResponseContentFolder {
    /**
    * Time of batch operation completion.
    */
    'completedAt': Date;
    /**
    * Links associated with batch operation.
    */
    'links'?: { [key: string]: string; };
    /**
    * Time of batch operation request.
    */
    'requestedAt'?: Date;
    /**
    * Results of batch operation.
    */
    'results': Array<ContentFolder>;
    /**
    * Time of batch operation start.
    */
    'startedAt': Date;
    /**
    * Status of batch operation.
    */
    'status': BatchResponseContentFolderStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "requestedAt",
            "baseName": "requestedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ContentFolder>",
            "format": ""
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchResponseContentFolderStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchResponseContentFolder.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BatchResponseContentFolderStatusEnum {
    Canceled = 'CANCELED',
    Complete = 'COMPLETE',
    Pending = 'PENDING',
    Processing = 'PROCESSING'
}

