/**
 * Site Search
 * Basepom for all HubSpot Projects
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentSearchResult } from '../models/ContentSearchResult';

export class PublicSearchResults {
    /**
    * The number of results returned in a single response.
    */
    'limit': number;
    /**
    * The starting point for the next set of results in pagination.
    */
    'offset': number;
    /**
    * The current page number in the paginated results.
    */
    'page': number;
    'results': Array<ContentSearchResult>;
    /**
    * The term used in the search query.
    */
    'searchTerm'?: string;
    /**
    * The total number of results found for the search term.
    */
    'total': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ContentSearchResult>",
            "format": ""
        },
        {
            "name": "searchTerm",
            "baseName": "searchTerm",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return PublicSearchResults.attributeTypeMap;
    }

    public constructor() {
    }
}
