/**
 * URL redirects
 * URL redirect operations
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class UrlMappingCreateRequestBody {
    'precedence'?: number;
    'isOnlyAfterNotFound'?: boolean;
    'isMatchFullUrl'?: boolean;
    'isMatchQueryString'?: boolean;
    'isPattern'?: boolean;
    'isTrailingSlashOptional'?: boolean;
    'isProtocolAgnostic'?: boolean;
    'routePrefix': string;
    'destination': string;
    'redirectStyle': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "precedence",
            "baseName": "precedence",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "isOnlyAfterNotFound",
            "baseName": "isOnlyAfterNotFound",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMatchFullUrl",
            "baseName": "isMatchFullUrl",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMatchQueryString",
            "baseName": "isMatchQueryString",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPattern",
            "baseName": "isPattern",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isTrailingSlashOptional",
            "baseName": "isTrailingSlashOptional",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isProtocolAgnostic",
            "baseName": "isProtocolAgnostic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "routePrefix",
            "baseName": "routePrefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirectStyle",
            "baseName": "redirectStyle",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return UrlMappingCreateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}

