/**
 * CRM Calling Extensions
 * Basepom for all HubSpot Projects
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ChannelConnectionSettingsResponse {
    /**
    * The date and time when the channel connection settings were created.
    */
    'createdAt': Date;
    /**
    * Indicates whether the channel connection settings are ready for use.
    */
    'isReady': boolean;
    /**
    * The date and time when the channel connection settings were last updated.
    */
    'updatedAt': Date;
    /**
    * The URL associated with the channel connection settings.
    */
    'url': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isReady",
            "baseName": "isReady",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelConnectionSettingsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
