/**
 * CRM Calling Extensions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ChannelConnectionSettingsRequest {
    /**
    * If true, this app will be considered to support channel connection
    */
    'isReady': boolean;
    /**
    * The URL to fetch phone numbers available for channel connection
    */
    'url': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isReady",
            "baseName": "isReady",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelConnectionSettingsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
