/**
 * Accounting Extension
 * These APIs allow you to interact with HubSpot\'s Accounting Extension. It allows you to: * Specify the URLs that HubSpot will use when making webhook requests to your external accounting system. * Respond to webhook calls made to your external accounting system by HubSpot 
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Lists the individual aspects of creating invoices that are enabled for the integration, as part of the create invoice flow in HubSpot.
*/
export class CreateInvoiceSubFeatures {
    /**
    * Indicates if a new customer can be created in the external accounting system.
    */
    'createCustomer': boolean;
    /**
    * Indicates if taxes can be specified by the HubSpot user for line items.
    */
    'taxes': boolean;
    /**
    * Indicates if the external accounting system supports fetching exchange rates when create an invoice in HubSpot for a customer billed in a different currency.
    */
    'exchangeRates': boolean;
    /**
    * Indicates if the external accounting system supports fetching payment terms.
    */
    'terms': boolean;
    /**
    * Indicates if a visible comment can be added to invoices.
    */
    'invoiceComments': boolean;
    /**
    * Indicates if invoice-level discounts can be added to invoices.
    */
    'invoiceDiscounts': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createCustomer",
            "baseName": "createCustomer",
            "type": "boolean"
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "boolean"
        },
        {
            "name": "exchangeRates",
            "baseName": "exchangeRates",
            "type": "boolean"
        },
        {
            "name": "terms",
            "baseName": "terms",
            "type": "boolean"
        },
        {
            "name": "invoiceComments",
            "baseName": "invoiceComments",
            "type": "boolean"
        },
        {
            "name": "invoiceDiscounts",
            "baseName": "invoiceDiscounts",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CreateInvoiceSubFeatures.attributeTypeMap;
    }
}

