/**
 * Accounting Extension
 * These APIs allow you to interact with HubSpot\'s Accounting Extension. It allows you to: * Specify the URLs that HubSpot will use when making webhook requests to your external accounting system. * Respond to webhook calls made to your external accounting system by HubSpot 
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class InvoiceUpdateResponse {
    'externalInvoiceNumber'?: string;
    'totalAmountBilled': number;
    'balanceDue': number;
    'currencyCode': string;
    'dueDate': string;
    'externalRecipientId': string;
    'receivedByRecipientDate'?: number;
    'externalCreateDateTime'?: number;
    'isVoided': boolean;
    'createdAt': Date;
    'updatedAt': Date;
    'archivedAt'?: Date;
    'archived': boolean;
    'externalAccountId': string;
    'invoiceStatus': InvoiceUpdateResponse.InvoiceStatusEnum;
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalInvoiceNumber",
            "baseName": "externalInvoiceNumber",
            "type": "string"
        },
        {
            "name": "totalAmountBilled",
            "baseName": "totalAmountBilled",
            "type": "number"
        },
        {
            "name": "balanceDue",
            "baseName": "balanceDue",
            "type": "number"
        },
        {
            "name": "currencyCode",
            "baseName": "currencyCode",
            "type": "string"
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "string"
        },
        {
            "name": "externalRecipientId",
            "baseName": "externalRecipientId",
            "type": "string"
        },
        {
            "name": "receivedByRecipientDate",
            "baseName": "receivedByRecipientDate",
            "type": "number"
        },
        {
            "name": "externalCreateDateTime",
            "baseName": "externalCreateDateTime",
            "type": "number"
        },
        {
            "name": "isVoided",
            "baseName": "isVoided",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "archivedAt",
            "baseName": "archivedAt",
            "type": "Date"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "externalAccountId",
            "baseName": "externalAccountId",
            "type": "string"
        },
        {
            "name": "invoiceStatus",
            "baseName": "invoiceStatus",
            "type": "InvoiceUpdateResponse.InvoiceStatusEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceUpdateResponse.attributeTypeMap;
    }
}

export namespace InvoiceUpdateResponse {
    export enum InvoiceStatusEnum {
        CREATED = <any> 'CREATED',
        SENT = <any> 'SENT',
        PAID = <any> 'PAID',
        CLOSED = <any> 'CLOSED',
        OVERDUE = <any> 'OVERDUE',
        VOIDED = <any> 'VOIDED',
        NONE = <any> 'NONE',
        UNPAID = <any> 'UNPAID'
    }
}
