/**
 * Accounting Extension
 * These APIs allow you to interact with HubSpot\'s Accounting Extension. It allows you to: * Specify the URLs that HubSpot will use when making webhook requests to your external accounting system. * Respond to webhook calls made to your external accounting system by HubSpot 
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The invoice data stored in HubSpot
*/
export class InvoiceReadResponse {
    /**
    * The invoice number. Note that this is _not_ the ID of the invoice, but the number that the billed customer will see.
    */
    'externalInvoiceNumber'?: string;
    /**
    * The total amount that this invoice is for.
    */
    'totalAmountBilled': number;
    /**
    * The remaining balance due for the invoice.
    */
    'balanceDue': number;
    /**
    * The ISO 4217 currency code that represents the currency of the invoice.
    */
    'currencyCode': string;
    /**
    * The due date of the invoice
    */
    'dueDate': string;
    /**
    * The id of the customer in the external accounting system that the invoice was sent to.
    */
    'externalRecipientId': string;
    /**
    * The datetime that that invoice was sent to the customer.
    */
    'receivedByRecipientDate'?: number;
    /**
    * The datetime that the invoice was created in the external accounting system.
    */
    'externalCreateDateTime'?: number;
    /**
    * Indicated is the invoice has been voided or not.
    */
    'isVoided': boolean;
    /**
    * The datetime that the invoice was created in HubSpot.
    */
    'createdAt': Date;
    /**
    * The datetime that the invoice was last updated in HubSpot.
    */
    'updatedAt': Date;
    'archivedAt'?: Date;
    'archived': boolean;
    /**
    * The id of the account in the external accounting system that this invoice is related to.
    */
    'externalAccountId': string;
    /**
    * The status of the invoice
    */
    'invoiceStatus': InvoiceReadResponse.InvoiceStatusEnum;
    /**
    * The id of this invoice in the external accounting system.
    */
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalInvoiceNumber",
            "baseName": "externalInvoiceNumber",
            "type": "string"
        },
        {
            "name": "totalAmountBilled",
            "baseName": "totalAmountBilled",
            "type": "number"
        },
        {
            "name": "balanceDue",
            "baseName": "balanceDue",
            "type": "number"
        },
        {
            "name": "currencyCode",
            "baseName": "currencyCode",
            "type": "string"
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "string"
        },
        {
            "name": "externalRecipientId",
            "baseName": "externalRecipientId",
            "type": "string"
        },
        {
            "name": "receivedByRecipientDate",
            "baseName": "receivedByRecipientDate",
            "type": "number"
        },
        {
            "name": "externalCreateDateTime",
            "baseName": "externalCreateDateTime",
            "type": "number"
        },
        {
            "name": "isVoided",
            "baseName": "isVoided",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "archivedAt",
            "baseName": "archivedAt",
            "type": "Date"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "externalAccountId",
            "baseName": "externalAccountId",
            "type": "string"
        },
        {
            "name": "invoiceStatus",
            "baseName": "invoiceStatus",
            "type": "InvoiceReadResponse.InvoiceStatusEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceReadResponse.attributeTypeMap;
    }
}

export namespace InvoiceReadResponse {
    export enum InvoiceStatusEnum {
        Created = <any> 'CREATED',
        Sent = <any> 'SENT',
        Paid = <any> 'PAID',
        Closed = <any> 'CLOSED',
        Overdue = <any> 'OVERDUE',
        Voided = <any> 'VOIDED',
        None = <any> 'NONE',
        Unpaid = <any> 'UNPAID'
    }
}
