/**
 * Marketing Emails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Paging } from '../models/Paging';
import { VersionPublicEmail } from '../models/VersionPublicEmail';

/**
* Response object for collections of marketing emails with pagination information.
*/
export class CollectionResponseWithTotalVersionPublicEmail {
    /**
    * Total number of content emails.
    */
    'total': number;
    'paging'?: Paging;
    /**
    * Collection of emails.
    */
    'results': Array<VersionPublicEmail>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "paging",
            "baseName": "paging",
            "type": "Paging",
            "format": ""
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<VersionPublicEmail>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionResponseWithTotalVersionPublicEmail.attributeTypeMap;
    }

    public constructor() {
    }
}
