/**
 * Marketing Emails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicFontStyle } from '../models/PublicFontStyle';

export class PublicButtonStyleSettings {
    'backgroundColor'?: any;
    'fontStyle'?: PublicFontStyle;
    'cornerRadius'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "backgroundColor",
            "baseName": "backgroundColor",
            "type": "any",
            "format": ""
        },
        {
            "name": "fontStyle",
            "baseName": "fontStyle",
            "type": "PublicFontStyle",
            "format": ""
        },
        {
            "name": "cornerRadius",
            "baseName": "cornerRadius",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PublicButtonStyleSettings.attributeTypeMap;
    }

    public constructor() {
    }
}

