/**
 * Domains
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { DomainCdnConfig } from './domainCdnConfig';
import { DomainSetupInfo } from './domainSetupInfo';

export class Domain {
    'portalId': number;
    'id': number;
    'created': number;
    'updated': number;
    'domain': string;
    'primaryLandingPage': boolean;
    'primaryEmail': boolean;
    'primaryBlog': boolean;
    'primaryBlogPost': boolean;
    'primarySitePage': boolean;
    'primaryKnowledge': boolean;
    'primaryLegacyPage': boolean;
    'primaryClickTracking': boolean;
    'fullCategoryKey': string;
    'secondaryToDomain': string;
    'isResolving': boolean;
    'isDnsCorrect': boolean;
    'manuallyMarkedAsResolving': boolean;
    'consecutiveNonResolvingCount': number;
    'sslCname': string;
    'isSslEnabled': boolean;
    'isSslOnly': boolean;
    'certificateId': number;
    'sslRequestId': number;
    'isUsedForBlogPost': boolean;
    'isUsedForSitePage': boolean;
    'isUsedForLandingPage': boolean;
    'isUsedForEmail': boolean;
    'isUsedForKnowledge': boolean;
    'setupTaskId': number;
    'isSetupComplete': boolean;
    'setUpLanguage': string;
    'teamIds': Array<number>;
    'actualCname': string;
    'correctCname': string;
    'actualIp': string;
    'apexResolutionStatus': Domain.ApexResolutionStatusEnum;
    'apexDomain': string;
    'publicSuffix': string;
    'apexIpAddresses': Array<string>;
    'siteId': number;
    'brandId': number;
    'deletable': boolean;
    'domainCdnConfig': DomainCdnConfig;
    'setupInfo': DomainSetupInfo;
    'derivedBrandName': string;
    'createdById': number;
    'updatedById': number;
    'label': string;
    'isAnyPrimary': boolean;
    'isLegacyDomain': boolean;
    'isInternalDomain': boolean;
    'isResolvingInternalProperty': boolean;
    'isResolvingIgnoringManuallyMarkedAsResolving': boolean;
    'isUsedForAnyContentType': boolean;
    'isLegacy': boolean;
    'authorAt': number;
    'cosObjectType': Domain.CosObjectTypeEnum;
    'cdnPurgeEmbargoTime': number;
    'isStagingDomain': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "portalId",
            "baseName": "portalId",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "primaryLandingPage",
            "baseName": "primaryLandingPage",
            "type": "boolean"
        },
        {
            "name": "primaryEmail",
            "baseName": "primaryEmail",
            "type": "boolean"
        },
        {
            "name": "primaryBlog",
            "baseName": "primaryBlog",
            "type": "boolean"
        },
        {
            "name": "primaryBlogPost",
            "baseName": "primaryBlogPost",
            "type": "boolean"
        },
        {
            "name": "primarySitePage",
            "baseName": "primarySitePage",
            "type": "boolean"
        },
        {
            "name": "primaryKnowledge",
            "baseName": "primaryKnowledge",
            "type": "boolean"
        },
        {
            "name": "primaryLegacyPage",
            "baseName": "primaryLegacyPage",
            "type": "boolean"
        },
        {
            "name": "primaryClickTracking",
            "baseName": "primaryClickTracking",
            "type": "boolean"
        },
        {
            "name": "fullCategoryKey",
            "baseName": "fullCategoryKey",
            "type": "string"
        },
        {
            "name": "secondaryToDomain",
            "baseName": "secondaryToDomain",
            "type": "string"
        },
        {
            "name": "isResolving",
            "baseName": "isResolving",
            "type": "boolean"
        },
        {
            "name": "isDnsCorrect",
            "baseName": "isDnsCorrect",
            "type": "boolean"
        },
        {
            "name": "manuallyMarkedAsResolving",
            "baseName": "manuallyMarkedAsResolving",
            "type": "boolean"
        },
        {
            "name": "consecutiveNonResolvingCount",
            "baseName": "consecutiveNonResolvingCount",
            "type": "number"
        },
        {
            "name": "sslCname",
            "baseName": "sslCname",
            "type": "string"
        },
        {
            "name": "isSslEnabled",
            "baseName": "isSslEnabled",
            "type": "boolean"
        },
        {
            "name": "isSslOnly",
            "baseName": "isSslOnly",
            "type": "boolean"
        },
        {
            "name": "certificateId",
            "baseName": "certificateId",
            "type": "number"
        },
        {
            "name": "sslRequestId",
            "baseName": "sslRequestId",
            "type": "number"
        },
        {
            "name": "isUsedForBlogPost",
            "baseName": "isUsedForBlogPost",
            "type": "boolean"
        },
        {
            "name": "isUsedForSitePage",
            "baseName": "isUsedForSitePage",
            "type": "boolean"
        },
        {
            "name": "isUsedForLandingPage",
            "baseName": "isUsedForLandingPage",
            "type": "boolean"
        },
        {
            "name": "isUsedForEmail",
            "baseName": "isUsedForEmail",
            "type": "boolean"
        },
        {
            "name": "isUsedForKnowledge",
            "baseName": "isUsedForKnowledge",
            "type": "boolean"
        },
        {
            "name": "setupTaskId",
            "baseName": "setupTaskId",
            "type": "number"
        },
        {
            "name": "isSetupComplete",
            "baseName": "isSetupComplete",
            "type": "boolean"
        },
        {
            "name": "setUpLanguage",
            "baseName": "setUpLanguage",
            "type": "string"
        },
        {
            "name": "teamIds",
            "baseName": "teamIds",
            "type": "Array<number>"
        },
        {
            "name": "actualCname",
            "baseName": "actualCname",
            "type": "string"
        },
        {
            "name": "correctCname",
            "baseName": "correctCname",
            "type": "string"
        },
        {
            "name": "actualIp",
            "baseName": "actualIp",
            "type": "string"
        },
        {
            "name": "apexResolutionStatus",
            "baseName": "apexResolutionStatus",
            "type": "Domain.ApexResolutionStatusEnum"
        },
        {
            "name": "apexDomain",
            "baseName": "apexDomain",
            "type": "string"
        },
        {
            "name": "publicSuffix",
            "baseName": "publicSuffix",
            "type": "string"
        },
        {
            "name": "apexIpAddresses",
            "baseName": "apexIpAddresses",
            "type": "Array<string>"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "number"
        },
        {
            "name": "brandId",
            "baseName": "brandId",
            "type": "number"
        },
        {
            "name": "deletable",
            "baseName": "deletable",
            "type": "boolean"
        },
        {
            "name": "domainCdnConfig",
            "baseName": "domainCdnConfig",
            "type": "DomainCdnConfig"
        },
        {
            "name": "setupInfo",
            "baseName": "setupInfo",
            "type": "DomainSetupInfo"
        },
        {
            "name": "derivedBrandName",
            "baseName": "derivedBrandName",
            "type": "string"
        },
        {
            "name": "createdById",
            "baseName": "createdById",
            "type": "number"
        },
        {
            "name": "updatedById",
            "baseName": "updatedById",
            "type": "number"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "isAnyPrimary",
            "baseName": "isAnyPrimary",
            "type": "boolean"
        },
        {
            "name": "isLegacyDomain",
            "baseName": "isLegacyDomain",
            "type": "boolean"
        },
        {
            "name": "isInternalDomain",
            "baseName": "isInternalDomain",
            "type": "boolean"
        },
        {
            "name": "isResolvingInternalProperty",
            "baseName": "isResolvingInternalProperty",
            "type": "boolean"
        },
        {
            "name": "isResolvingIgnoringManuallyMarkedAsResolving",
            "baseName": "isResolvingIgnoringManuallyMarkedAsResolving",
            "type": "boolean"
        },
        {
            "name": "isUsedForAnyContentType",
            "baseName": "isUsedForAnyContentType",
            "type": "boolean"
        },
        {
            "name": "isLegacy",
            "baseName": "isLegacy",
            "type": "boolean"
        },
        {
            "name": "authorAt",
            "baseName": "authorAt",
            "type": "number"
        },
        {
            "name": "cosObjectType",
            "baseName": "cosObjectType",
            "type": "Domain.CosObjectTypeEnum"
        },
        {
            "name": "cdnPurgeEmbargoTime",
            "baseName": "cdnPurgeEmbargoTime",
            "type": "number"
        },
        {
            "name": "isStagingDomain",
            "baseName": "isStagingDomain",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Domain.attributeTypeMap;
    }
}

export namespace Domain {
    export enum ApexResolutionStatusEnum {
        INELIGIBLE = <any> 'INELIGIBLE',
        SUGGESTRESOLVING = <any> 'SUGGEST_RESOLVING',
        ALREADYRESOLVING = <any> 'ALREADY_RESOLVING',
        ERROR = <any> 'ERROR'
    }
    export enum CosObjectTypeEnum {
        CONTENT = <any> 'CONTENT',
        EXTENSIONRESOURCE = <any> 'EXTENSION_RESOURCE',
        LAYOUT = <any> 'LAYOUT',
        CUSTOMWIDGET = <any> 'CUSTOM_WIDGET',
        WIDGET = <any> 'WIDGET',
        FORM = <any> 'FORM',
        PLACEMENT = <any> 'PLACEMENT',
        IMAGE = <any> 'IMAGE',
        DOMAINSETTINGS = <any> 'DOMAIN_SETTINGS',
        SITESETTINGS = <any> 'SITE_SETTINGS',
        EMAILADDRESS = <any> 'EMAIL_ADDRESS',
        WORKFLOW = <any> 'WORKFLOW',
        HUBDBTABLE = <any> 'HUBDB_TABLE',
        REDIRECTURL = <any> 'REDIRECT_URL',
        DESIGNFOLDER = <any> 'DESIGN_FOLDER',
        SITEMAP = <any> 'SITE_MAP',
        DOMAIN = <any> 'DOMAIN',
        BLOG = <any> 'BLOG',
        FILE = <any> 'FILE',
        FOLDER = <any> 'FOLDER',
        SITEMENU = <any> 'SITE_MENU',
        THEME = <any> 'THEME',
        CONTENTGROUP = <any> 'CONTENT_GROUP',
        FOLLOWME = <any> 'FOLLOW_ME',
        KNOWLEDGEBASE = <any> 'KNOWLEDGE_BASE',
        LISTMEMBERSHIP = <any> 'LIST_MEMBERSHIP',
        CONTACTMEMBERSHIP = <any> 'CONTACT_MEMBERSHIP',
        PASSWORDPROTECTED = <any> 'PASSWORD_PROTECTED',
        UNRESTRICTEDACCESS = <any> 'UNRESTRICTED_ACCESS',
        MARKETPLACELISTING = <any> 'MARKETPLACE_LISTING',
        LAYOUTSECTION = <any> 'LAYOUT_SECTION',
        THEMESETTINGS = <any> 'THEME_SETTINGS',
        VIDEOPLAYER = <any> 'VIDEO_PLAYER',
        URLMAPPING = <any> 'URL_MAPPING',
        KNOWLEDGECATEGORY = <any> 'KNOWLEDGE_CATEGORY',
        KNOWLEDGEHOMEPAGECATEGORY = <any> 'KNOWLEDGE_HOMEPAGE_CATEGORY',
        RAWASSET = <any> 'RAW_ASSET',
        GLOBALCONTENT = <any> 'GLOBAL_CONTENT',
        HUBDBTABLEROW = <any> 'HUBDB_TABLE_ROW',
        BLOGAUTHOR = <any> 'BLOG_AUTHOR',
        SERVERLESSFUNCTION = <any> 'SERVERLESS_FUNCTION',
        KNOWLEDGECATEGORYTRANSLATION = <any> 'KNOWLEDGE_CATEGORY_TRANSLATION'
    }
}
